name: Fetch Exchange Rates

on:
  schedule:
    - cron: '0 0 * * *' # This will run the action every day at midnight UTC
  workflow_dispatch: # Allows you to run the workflow manually from GitHub

jobs:
  fetch_rates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Dart
      uses: subosito/dart-action@v2
      with:
        dart: '2.15.0' # Specify the Dart version you want to use

    - name: Install dependencies
      run: dart pub get

    - name: Run fetch exchange rates
      env:
        FREECURRENCYAPI_KEY: ${{ secrets.FREECURRENCYAPI_KEY }}
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: dart run lib/fetch_exchange_rates.dart