name: Fetch Exchange Rates

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v2
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Run fetch exchange rates script
        run: dart run lib/fetch_exchange_rates.dart
        env:
          FREECURRENCYAPI_KEY: ${{ secrets.FREECURRENCYAPI_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          