name: Fetch Exchange Rates

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest' # Specify a version if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Run fetch exchange rates script
        run: flutter run lib/fetch_exchange_rates.dart
        env:
          FREECURRENCYAPI_KEY: ${{ secrets.FREECURRENCYAPI_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}